#! /bin/sh

# Define absolute path to RBNB (so that this script can be
# launched by root at bootup w/o needing any other variables
# defined.
RBNB=/home/fedora/INDS/Utility/RBNB/V3.1B3
export JAVA_OPTS=-mx384M
export CATALINA_HOME=$RBNB/apache-tomcat-5.5.12
export JAVA_HOME=/usr
$CATALINA_HOME/bin/shutdown.sh
