#!/bin/sh

#chkconfig: 5 99 05
#description: Intelligent Network Data Server (INDS)

INDS_HOME=/home/fedora/INDS

case "$1" in
  "start")
     if [ ! -f $INDS_HOME/start_inds ]
     then
         echo "INDS startup: cannot start (could not find start_inds script)"
         exit
     fi
     $INDS_HOME/start_inds
     ;;
  "stop")
     if [ ! -f $INDS_HOME/kill_inds ]
     then
         echo "INDS stop: cannot stop (could not find kill_inds script)"
         exit
     fi
     $INDS_HOME/kill_inds
     ;;
  "status")
     is_running=`ps axww | grep java | grep INDS`
     if [ ${#is_running} -eq 0 ]
     then
       echo $"INDS is not running"
     else
       echo $"INDS is running"
     fi
     ;;
  *)
     echo $"Usage: $0 {start|stop|status}"
esac
